### ISSUE TITLE
Ubuntu22.04用docker部署出错

### ISSUE THREAD

**Issue by xiiizoux** [Moonvy/OpenPromptStudio#18]
[plugin:vite:import-analysis] Failed to resolve import "../../ParsePrompts" from "src/Compoents/PromptEditor/Lib/parsePrompts/parsers/Midjourney/index.ts". Does the file exist?
/app/src/Compoents/PromptEditor/Lib/parsePrompts/parsers/Midjourney/index.ts:1:44
1  |  import { PromptWordType } from "../../ParsePrompts";
   |                                  ^
2  |  import { translateZh2En } from "../../../translatePrompts";
3  |  export async function midjourneyParse(text, options) {
    at formatError (file:///app/node_modules/vite/dist/node/chunks/dep-665b0112.js:40782:46)
    at TransformContext.error (file:///app/node_modules/vite/dist/node/chunks/dep-665b0112.js:40778:19)
    at normalizeUrl (file:///app/node_modules/vite/dist/node/chunks/dep-665b0112.js:37514:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async TransformContext.transform (file:///app/node_modules/vite/dist/node/chunks/dep-665b0112.js:37648:47)
    at async Object.transform (file:///app/node_modules/vite/dist/node/chunks/dep-665b0112.js:41031:30)
    at async loadAndTransform (file:///app/node_modules/vite/dist/node/chunks/dep-665b0112.js:37292:29
Click outside or fix the code to dismiss.
You can also disable this overlay by setting server.hmr.overlay to false in vite.config.js.

**Comment by var618** [comment]
可能是windows下**大小写**路径不区分，而到linux平台区分大小写引起的。

**Comment by yArna** [comment]
这个修复了，请 pull 最新版本
