### ISSUE TITLE
部署运行出错：Failed to resolve import "../../ParsePrompts"

### ISSUE THREAD

**Issue by Luo-hongyi** [Moonvy/OpenPromptStudio#3]
```bash
$ npm run dev

> @moonvy/open-prompt-studio@1.0.7 dev
> vite dev --host


  VITE v3.1.0  ready in 746 ms

  ➜  Local:   http://localhost:12345/apps/ops/
  ➜  Network: http://x.x.x.x:12345/apps/ops/
  ➜  Network: http://x.x.x.x:12345/apps/ops/
Failed to resolve import "../../ParsePrompts" from "src/Compoents/PromptEditor/Lib/parsePrompts/parsers/Midjourney/index.ts". Does the file exist?
4:37:41 AM [vite] Internal server error: Failed to resolve import "../../ParsePrompts" from "src/Compoents/PromptEditor/Lib/parsePrompts/parsers/Midjourney/index.ts". Does the file exist?
  Plugin: vite:import-analysis
  File: /root/OpenPromptStudio/src/Compoents/PromptEditor/Lib/parsePrompts/parsers/Midjourney/index.ts
  1  |  import { PromptWordType } from "../../ParsePrompts";
     |                                  ^
  2  |  import { translateZh2En } from "../../../translatePrompts";
  3  |  export async function midjourneyParse(text, options) {
      at formatError (file:///root/OpenPromptStudio/node_modules/vite/dist/node/chunks/dep-665b0112.js:40782:46)
      at TransformContext.error (file:///root/OpenPromptStudio/node_modules/vite/dist/node/chunks/dep-665b0112.js:40778:19)
      at normalizeUrl (file:///root/OpenPromptStudio/node_modules/vite/dist/node/chunks/dep-665b0112.js:37514:33)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async TransformContext.transform (file:///root/OpenPromptStudio/node_modules/vite/dist/node/chunks/dep-665b0112.js:37648:47)
      at async Object.transform (file:///root/OpenPromptStudio/node_modules/vite/dist/node/chunks/dep-665b0112.js:41031:30)
      at async loadAndTransform (file:///root/OpenPromptStudio/node_modules/vite/dist/node/chunks/dep-665b0112.js:37292:29)
```

**Comment by doucat** [comment]
import "../../ParsePrompts" 改成parsePrompts

**Comment by ottoskyer** [comment]
改了，不报错，但页面很难打开
