### ISSUE TITLE
求助：部署云服务器报错

### ISSUE THREAD

**Issue by RichForever888** [Moonvy/OpenPromptStudio#84]
使用 npm run start 运行后：
```
ubuntu@10-7-118-179:/www/wwwroot/XXXXX/app/OpenPromptStudio-master$ npm run start
npm WARN config init.module Use `--init-module` instead.

> @moonvy/open-prompt-studio@1.4.4 start
> npm-run-all --parallel dev serve

npm WARN config init.module Use `--init-module` instead.
npm WARN config init.module Use `--init-module` instead.

> @moonvy/open-prompt-studio@1.4.4 dev
> vite --host 0.0.0.0


> @moonvy/open-prompt-studio@1.4.4 serve
> jiti ./server/index.ts

failed to load config from /www/wwwroot/1aibox.com/app/OpenPromptStudio-master/vite.config.ts
error when starting dev server:
Error: EACCES: permission denied, open '/www/wwwroot/XXXXX/app/OpenPromptStudio-master/vite.config.ts.timestamp-1686848545438-ee8f4fb8c55f6.mjs'
ERROR: "dev" exited with 1.
```

**Comment by RichForever888** [comment]
使用 sudo npm run start 运行后：

```
npm WARN config init.module Use `--init-module` instead.

> @moonvy/open-prompt-studio@1.4.4 start
> npm-run-all --parallel dev serve

npm WARN config init.module Use `--init-module` instead.
npm WARN config init.module Use `--init-module` instead.

> @moonvy/open-prompt-studio@1.4.4 serve
> jiti ./server/index.ts


> @moonvy/open-prompt-studio@1.4.4 dev
> vite --host 0.0.0.0

Port 12833 is in use, trying another one...

  VITE v4.3.1  ready in 293 ms

  ➜  Local:   http://localhost:12834/apps/ops/
  ➜  Network: http://10.7.118.179:12834/apps/ops/
  ➜  press h to show help
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::39011
    at Server.setupListenHandle [as _listen2] (node:net:1740:16)
    at listenInCluster (node:net:1788:12)
    at Server.listen (node:net:1876:7)
    at Function.listen (/www/wwwroot/1aibox.com/app/OpenPromptStudio-master/node_modules/express/lib/application.js:635:24)
    at /www/wwwroot/1aibox.com/app/OpenPromptStudio-master/server/index.ts:27:5
    at jiti (/www/wwwroot/1aibox.com/app/OpenPromptStudio-master/node_modules/jiti/dist/jiti.js:1:247502)
    at Object.<anonymous> (/www/wwwroot/1aibox.com/app/OpenPromptStudio-master/node_modules/jiti/bin/jiti.js:16:1)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1767:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '::',
  port: 39011
}

Node.js v18.16.0
ERROR: "serve" exited with 1.
```

39011端口是打开的
